### ISSUE TITLE
Robosense data failed

### ISSUE THREAD

**Issue by CharlieV5** [HViktorTsoi/PV-LIO#3] opened 2023-07-15 10:53 UTC
通过百度网盘下载的三个Robosense数据
![2023-07-15 18-48-53 的屏幕截图](https://github.com/HViktorTsoi/PV-LIO/assets/8245892/cc706973-9a4e-4c28-bb78-7a62430744ed)
启动mapping_robosense.launch后崩溃：
![2023-07-15 18-51-12 的屏幕截图](https://github.com/HViktorTsoi/PV-LIO/assets/8245892/4e0bd7fb-74ca-4f0a-b08d-abf2dc8d35a0)
![2023-07-15 18-51-18 的屏幕截图](https://github.com/HViktorTsoi/PV-LIO/assets/8245892/75404367-4ea6-4ce3-b171-6f0b23bc421c)

**Comment by CharlieV5** [comment] 2023-07-15 10:58
系统为Ubuntu20.04, Noetic

**Comment by Yeah2333** [comment] 2023-07-15 12:36
我也遇到了一样的问题。
![image](https://github.com/HViktorTsoi/PV-LIO/assets/22851247/72768dd3-3e9c-4c65-a852-8b302398f646)

**Comment by HViktorTsoi** [comment] 2023-07-15 13:43
We tested our implement with Ubuntu18.04 and row melodic, this may be some issue with the default Eigen version, we will soon test it on 20.04

**Comment by HViktorTsoi** [comment] 2023-07-15 13:47
> 系统为Ubuntu20.04, Noetic

Could you tell us which version of Eigen you are using?

**Comment by CharlieV5** [comment] 2023-07-15 14:38
> > 系统为Ubuntu20.04, Noetic
> 
> Could you tell us which version of Eigen you are using?

Eigen 3.4.0

**Comment by JJho1314** [comment] 2023-07-15 15:31
Hi，I meet same trouble with ubuntu 18.04 and ROS melodic, and the version of my Eigen is 3.3.7, thanks

**Comment by HViktorTsoi** [comment] 2023-07-16 08:19
Hey guys, I've tested with Eigen 3.3.7 / 3.3.4 and it works fine with both version. What is your PCL version? And could you upload the whole output from the first few seconds of the algorithm's execution?

**Comment by Yeah2333** [comment] 2023-07-16 09:00
I meet same trouble with ubuntu18.04, ros melodic, eigen 3.3.7

**Comment by Yeah2333** [comment] 2023-07-16 10:12
The code output No effective points , and then crush. I check the code, it seems no enough measurement ptpl. And i check the code , in this line https://github.com/HViktorTsoi/PV-LIO/blob/a4d2dbf0f5a65446cd36af3dfca7416d9ea38919/include/voxel_map_util.hpp#L703C36-L703C36. This line check p2plane dist, but plane.radius get a very low value.
![image](https://github.com/HViktorTsoi/PV-LIO/assets/22851247/d34be86e-8a54-45f5-922b-5855cd144ff4)
So, i edit this line just using 0.1 instead of plane.radius. But the code also crush.
And i found rviz have some wrong plane. So i think code may have some troubel in plane extract. 
![image](https://github.com/HViktorTsoi/PV-LIO/assets/22851247/9e64f725-dc15-4ff0-b41f-ea5c443d2fd7)

**Comment by Yeah2333** [comment] 2023-07-16 10:14
By the way ,before code crush. i have some eigen aligned problem. I fix this using align allocater

**Comment by 885288421** [comment] 2023-07-17 02:29
Hi，This is an excellent project, thank you for your contribution！but I meet same trouble with ubuntu 20.04 and ROS nortic, and the version of my Eigen is 3.3.7, pcl is 1.10.0,I record my rosbag outdoors,I would like to know how to fix this.thanks

**Comment by HViktorTsoi** [comment] 2023-07-17 07:58
Hi, a tiny but important question, for those using the demo rosbag dataset, did you play the bags in order with `rosbag play *.bag`? There may be some issues if you play the second or the third bag alone, because the LIO currently requires static initialization.

**Comment by HViktorTsoi** [comment] 2023-07-17 08:01
> Hi，This is an excellent project, thank you for your contribution！but I meet same trouble with ubuntu 20.04 and ROS nortic, and the version of my Eigen is 3.3.7, pcl is 1.10.0,I record my rosbag outdoors,I would like to know how to fix this.thanks

Hi, could you upload the rosbag and LiDAR-IMU extrinsic parameter for us to debug? That will be a lot more efficient for addressing this issue.

**Comment by HViktorTsoi** [comment] 2023-07-17 09:01
> The lidar is robosense,but we used a rospackage rs_to_velodyne to convert the data ,the imu topic is"/sensor/imu/imu_data",the lidat topic is "/sensor/lidar/points",the rosbag url is :https://pan.baidu.com/s/1BmncWoxoeeMgn1BMP7VUnA password: 3nst. extrinsic_T: [-0.376489, -0.0505456, -0.109697 ] extrinsic_R: [ 1, 0, 0, 0, 1, 0, 0, 0, 1 ] I hope to hear good news,thanks!

Hi, we foud the problem, it's because of the parameter setting, the default parameter we provide is for narrow indoor environment, but your test scene is a largescale outdoor scene(and the LiDAR is sparse), there for the `down_sample_size` and `voxel_size` are too small for such scenario. After increasing these two parameter, it runs normally.
![Screenshot from 2023-07-17 16-45-19](https://github.com/HViktorTsoi/PV-LIO/assets/25725035/68ec97d3-f1f7-4520-a804-5d04a17fd9d3)
![Screenshot from 2023-07-17 16-50-00](https://github.com/HViktorTsoi/PV-LIO/assets/25725035/2e12b3e9-73c4-46b7-bc38-2bd815f6c2e9)

We have provide a launch and corresponding config file called `robosense_outdoor.yaml`, please pull the update repo, and modify the config file path in `robosense.launch` to   
```
    <rosparam command="load" file="$(find pv_lio)/config/robosense_outdoor.yaml"/>
```
You may also try to tune the parameter setting for better performances.

**Comment by 885288421** [comment] 2023-07-17 10:58
hi,thanks for your help. the problem still exists.Do you test on noetic,I will change the environment to test the rosbag .

**Comment by HViktorTsoi** [comment] 2023-07-17 11:33
> hi,thanks for your help. the problem still exists.Do you test on noetic,I will change the environment to test the rosbag .

We tested with melodic.

**Comment by CharlieV5** [comment] 2023-07-18 06:05
I have test in Ubuntu18.04, ROS melodic. The program runs well. So probably the problem is about the system environment.

**Comment by HViktorTsoi** [comment] 2023-07-18 11:48
Hey guys, we reproduce this bug on Ubuntu 20.04, it is because some numerical type convention issue of GCC 9.3 and the default Eigen of Ubuntu 20.04, which causing abnormal result while calculating the voxel coordinates of points. 

We have pushed a fixed for this issue. Please pull the latest code and test it. It would be very nice if you let us know the test result.

**Closed** 2023-07-18 12:32 UTC

**Comment by alwynmathew** [comment] 2023-09-29 10:07
@HViktorTsoi I get the below error with `roslaunch pv_lio mapping_robosense.launch` and `rosbag play staircase_crazy_rotation/2022-08-30-20-33-52_0.bag`.

Ubuntu 20.04
ROS Noetic
Eigen 3.3.7
PCL 1.10

```
pv_lio_node: /usr/include/eigen3/Eigen/src/Core/DenseStorage.h:128: Eigen::internal::plain_array<T, Size, 
MatrixOrArrayOptions, 32>::plain_array() [with T = double; int Size = 36; int MatrixOrArrayOptions = 0]: 
Assertion `(internal::UIntPtr(eigen_unaligned_array_assert_workaround_gcc47(array)) & (31)) == 0 && 
"this assertion is explained here: " "http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html" " 
**** READ THIS WEB PAGE !!! ****"' failed.
[pv_lio_node-1] process has died [pid 23511, exit code -6, cmd /home/alwyn/catkin_pv/devel/lib/pv_lio/pv_lio_node 
__name:=pv_lio_node __log:=/home/alwyn/.ros/log/95c3ca40-5e20-11ee-9ce3-2b06debad6a1/pv_lio_node-1.log].
```

**Comment by alexjunholee** [comment] 2024-05-20 05:39
@alwynmathew try upgrading to C++17, it is explained in that eigen website link.
